server.port = 8080
spring.application.name = North Harbor Demo

server.servlet.context-path =/northharbordemo
spring.mvc.view.prefix = /WEB-INF/jsp/
spring.mvc.view.suffix = .jsp

exchange.rate.api.endpoint = http://api.exchangeratesapi.io/v1/
exchange.rate.api.key = 4dac950fc5f8b8b10571bcf8251d65a6
security.allowed.origins.urlList = http://localhost:4200