server.port = 8080
server.forward-headers-strategy=native
server.tomcat.redirect-context-root=false

spring.application.name = North Harbor Demo

spring.config.import[0]=aws-secretsmanager:rds!db-0fa33b77-4850-4ddc-9e22-e451ec2cdd93?prefix=spring.datasource.
spring.config.import[1]=aws-secretsmanager:ex_rates_api_key

spring.cloud.aws.region.static=us-east-2

server.servlet.context-path =/northharbordemo
spring.mvc.view.prefix = /WEB-INF/jsp/
spring.mvc.view.suffix = .jsp

exchange.rate.api.endpoint = http://api.exchangeratesapi.io/v1/

security.allowed.origins.urlList = http://localhost:4200

spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://database-1.c50mucw4mh5n.us-east-2.rds.amazonaws.com:3306/northharbordb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=8000
spring.datasource.hikari.validation-timeout=5000